### ISSUE TITLE
App crashing on empty username

### ISSUE THREAD

**Issue by viralvaghela** [Jay-Vaghela0/Chat_Book#1]
the app is crashing if the user enters empty username and open the chat screen.

2020-10-01 10:16:04.055 6322-6322/? E/ela.chatbookml: Unknown bits set in runtime_flags: 0x8000
2020-10-01 10:16:04.707 6322-6353/com.jayvaghela.chatbookmlx E/EGL-gift: Cannot load register apis
2020-10-01 10:16:04.733 6322-6353/com.jayvaghela.chatbookmlx E/gralloc: Arm Module v1.0
2020-10-01 10:16:04.733 6322-6353/com.jayvaghela.chatbookmlx E/ion: ioctl c0044901 failed with code -1: Invalid argument
2020-10-01 10:16:14.540 6322-6322/com.jayvaghela.chatbookmlx E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.jayvaghela.chatbookmlx, PID: 6322
    java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
        at com.google.firebase.database.collection.ArraySortedMap$1.next(com.google.firebase:firebase-database-collection@@16.0.1:161)
        at com.google.firebase.database.collection.ArraySortedMap$1.next(com.google.firebase:firebase-database-collection@@16.0.1:151)
        at com.google.firebase.database.snapshot.ChildrenNode$NamedNodeIterator.next(com.google.firebase:firebase-database@@19.2.0:59)
        at com.google.firebase.database.snapshot.ChildrenNode$NamedNodeIterator.next(com.google.firebase:firebase-database@@19.2.0:44)
        at com.google.firebase.database.DataSnapshot$1$1.next(com.google.firebase:firebase-database@@19.2.0:282)
        at com.google.firebase.database.DataSnapshot$1$1.next(com.google.firebase:firebase-database@@19.2.0:273)
        at com.jayvaghela.chatbookmlx.Chat_Room.append_chat_conversation(Chat_Room.java:118)
        at com.jayvaghela.chatbookmlx.Chat_Room.access$400(Chat_Room.java:29)
        at com.jayvaghela.chatbookmlx.Chat_Room$2.onChildAdded(Chat_Room.java:84)
        at com.google.firebase.database.core.ChildEventRegistration.fireEvent(com.google.firebase:firebase-database@@19.2.0:79)
        at com.google.firebase.database.core.view.DataEvent.fire(com.google.firebase:firebase-database@@19.2.0:63)
        at com.google.firebase.database.core.view.EventRaiser$1.run(com.google.firebase:firebase-database@@19.2.0:55)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:227)
        at android.app.ActivityThread.main(ActivityThread.java:7822)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1026)

I would like to fix this bug.

**Comment by Jay-Vaghela0** [comment]
thanks
